c = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(c))

print(c, 'é um titulo?', c.istitle())
print(c, 'é alfanumérico? ', c.isalnum())
print(c, 'tem apenas letras? ', c.isalpha())
print(c, 'tem apenas numeros?', c.isnumeric())
print(c, 'não tem acentos? ', c.isascii())
print(c, 'é decimal?', c.isdecimal())
print(c, 'é digitado?', c.isdigit())
print(c, 'tem apenas letras minusculas?', c.islower())
print(c, 'tem apenas letras maiúsculas?', c.isupper())
print(c, 'aparece na tela?', c.isprintable())
print(c, 'é um espaço?', c.isspace())
